server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bs_ems?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /**



